research_task:
  description: >
    Find 4-5 interesting and recent facts about {topic} as of year 2026.
  expected_output: >
    A bullet list of 4-5 facts

writer_task:
  description: >
    Write a 120-word blog post summary about {topic} using the facts from the research.
  expected_output: >
    A blog post summary